---
- name: Migrate content hosts from old satellite into the new Satellite server
  hosts: all

  tasks:

    - name : Unregister from the satellite and clean subscriptions
      command:  >
        rpm -qe katello-ca-consumer-ariel.nleroux.ca-1.0-1.noarch ;
        subscription-manager remove --all ;
        subscription-manager unregister 2>/dev/null ;
        rm -fr /var/cache/dnf/* ;
        subscription-manager clean ;
        yum clean all 
      ignore_errors: true
      
    - name: "Localinstall the satellite katello RPM"
      ansible.builtin.dnf:
        name: http://ariel.nleroux.ca/pub/katello-ca-consumer-latest.noarch.rpm 
        state: present
        disable_gpg_check: true

    - name: "Register to the Satellite with the activation key and organization"
      community.general.redhat_subscription:
        activationkey: "ak8"
        org_id: "ACME"
        force_register: true
        state: "present"

    - name: "Register the output from yum repolist all "
      command: yum repolist all
      register: yum_respos

    - name: "Print out the list of respos for the system"
      debug:  var=yum_repos

      
         





      