---
- name: Migrate content hosts from old satellite into the new Satellite server
  hosts: all

  tasks:
    - name : unregister from the satellite
      command:  >
        subscription-manager remove --all ;
        subscription-manager unregister 2>/dev/null ;
        rm -fr /var/cache/dnf/* ;
        subscription-manager clean ;
        yum clean all 
      ignore_errors: true

