---
- name: Migrate content hosts from old satellite into the new Satellite server
  hosts: all
  vars:
    katello_old_to_remove: katello-ca-consumer-ariel.nleroux.ca-1.0-1.noarch
    katello_new_uri: http://ariel.nleroux.ca/pub/katello-ca-consumer-latest.noarch.rpm
    satellite_act_key: ak8
    satellite_org_id: ACME

  tasks:

    - name: "Unregister from the Satellite "
      community.general.redhat_subscription:
        state: "absent"

    - name: "remove rpm"
      ansible.builtin.yum:
        name: "{{ katello_old_to_remove }}"
        state: "absent"
      ignore_errors: true

    - name : "Perform cleanup"
      command:  >
        rm -fr /var/cache/dnf/* ; 
        subscription-manager clean ;
        yum clean all
      ignore_errors: true
      
    - name: "Localinstall the satellite katello RPM"
      ansible.builtin.dnf:
        name: "{{ katello_new_uri }}"
        state: present
        disable_gpg_check: true

    - name: "Register to the Satellite with the activation key and organization"
      community.general.redhat_subscription:
        activationkey: "{{ satellite_act_key }}"
        org_id: "ACME"
        state: "{{ satellite_org_id }}"

    - name: "Register the output from yum repolist all "
      shell: yum repolist all
      register: command_output

    - name: "Print out the list of respos for the system"
      debug:  
              var: command_output.stdout_lines
