---
- name: Migrate content hosts from old satellite into the new Satellite server
  hosts: all

  tasks:

    - name: "Unregister from the Satellite "
      community.general.redhat_subscription:
        state: "absent"

    - name: "remove rpm"
      ansible.builtin.yum:
        name: katello-ca-consumer-ariel.nleroux.ca-1.0-1.noarch
        state: "absent"
      ignore_errors: true

    - name : "Perform cleanup"
      command:  >
        rm -fr /var/cache/dnf/* ; 
        subscription-manager clean ;
        yum clean all
      ignore_errors: true
      
    - name: "Localinstall the satellite katello RPM"
      ansible.builtin.dnf:
        name: http://ariel.nleroux.ca/pub/katello-ca-consumer-latest.noarch.rpm 
        state: present
        disable_gpg_check: true

    - name: "Register to the Satellite with the activation key and organization"
      community.general.redhat_subscription:
        activationkey: "ak8"
        org_id: "ACME"
        state: "present"

    - name: "Register the output from yum repolist all "
      shell: yum repolist all
      register: command_output

    - name: "Print out the list of respos for the system"
      debug:  
              var: command_output.stdout_lines
