---
- name: Migrate content hosts from old satellite into the new Satellite server
  hosts: all
  vars:
    old_package: cb-psc-sensor
    new_local_package: /softwares/CarbonBlack/cb-psc-sensor-2.14.0-1321525.el7.x86_64.rpm

  tasks:

    - name: "remove the old package"
      ansible.builtin.yum:
        name: "{{ old_package }}"
        state: "absent"
    

    - name: "remove the old package"
      ansible.builtin.yum:
        name: "{{ new_local_package }}"
        state: "present"
  